export const itemData = [
  {
    id: 1,
    title: "Bird Vase",
    img: "images/item1.webp",
    price: 10,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Pendulum Candles",
    img: "images/item2.jpeg",
    price: 20,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Plant Pot Gold",
    img: "images/item3.jfif",
    price: 28,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Moon Lamp",
    img: "images/item4.webp",
    price: 9,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Vase",
    img: "images/item5.jfif",
    price: 7,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Vase Thinking",
    img: "images/item6.webp",
    price: 15,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Gazelle",
    img: "images/item7.jpg",
    price: 23,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Plant Pot White",
    img: "images/item8.webp",
    price: 30,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Indoor Plant",
    img: "images/item9.jpg",
    price: 13,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Linked Square",
    img: "images/item10.webp",
    price: 18,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Handmade Bathroom Set",
    img: "images/item11.jpg",
    price: 8,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "High Grade Statue Crystal",
    img: "images/item12.jpg",
    price: 25,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: "Pinecone Ceramic",
    img: "images/item13.jpg",
    price: 20,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: "Vase Pampas Grass",
    img: "images/item14.jfif",
    price: 13,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: "Wooden Vases",
    img: "images/item15.jpg",
    price: 15,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const itemDetail = [
  {
    id: 1,
    title: "Bird Vase",
    img: "images/item1.webp",
    price: 10,
    info: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque amet eaque impedit, obcaecati totam atque recusandae libero qui adipisci architecto necessitatibus? Ipsam cum consequatur deserunt itaque placeat molestiae laboriosam tenetur.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const aboutData = [
  {
    id: 1,
    title: "80+ BRANDS",
    img: "images/brands.jfif",
    info: "A wide selection of international design brands.",
  },
  {
    id: 2,
    title: "1000+ PRODUCTS",
    img: "images/products.jpg",
    info: "A huge virtual showroom for you to browse at any time.",
  },
  {
    id: 3,
    title: "INTERNI DESIGN FACTORY",
    img: "images/factory.jpg",
    info: "A huge design centre where ideas come to life from our Creative Team.",
  },
  {
    id: 4,
    title: "INTERNI MATERIALS GALLERY",
    img: "images/gallery.jpg",
    info: "A gallery dedicated to coverings and materials used to create custom-made interiors.",
  },
];
